import { SiteHeader } from "@/app/components/site-header";
import { currentUser } from "@/lib/entitlements";
import { ACTIVATION_PRICE_CENTS, RENEWAL_PRICE_CENTS, moneyFromCents } from "@/lib/billing";
import Link from "next/link";
import { MarketingSelectorDemo } from "@/app/components/marketing-selector-demo";
import { OrchestrationOrbit } from "@/app/components/orchestration-orbit";
import { TimeEstimator } from "@/app/components/time-estimator";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const user = await currentUser();
  return <><SiteHeader signedIn={Boolean(user)} /><main className="marketing-main">
    <section className="marketing-hero marketing-hero--orbit" aria-labelledby="hero-title">
      <div className="hero-copy"><p className="hero-context">Para quem cria sites com IA e quer parar de improvisar</p><h1 id="hero-title">Transforme referências soltas em um processo que a IA consegue executar.</h1><p className="hero-lead">O Orquestrador reúne skills, fontes e critérios em uma seleção clara. Você decide o objetivo, revisa o que será usado e chega ao chat com menos procura e mais direção.</p><div className="hero-actions"><Link className="button button--primary button--large" href={user ? "/painel" : "/entrar?intent=signup"}>{user ? "Abrir painel" : "Começar meu processo"}</Link><a className="button button--outline button--large" href="#experimente">Testar a seleção</a></div><div className="hero-contract"><span>Você decide</span><span>O sistema organiza</span><span>A IA recebe contexto</span></div></div>
      <OrchestrationOrbit />
    </section>

    <section className="sales-shift" id="como-funciona" aria-labelledby="shift-title"><div className="sales-shift__intro"><h2 id="shift-title">O problema não é falta de ferramenta. É começar sem um processo.</h2><p>Quando cada projeto exige procurar novamente fontes, lembrar boas práticas e reescrever instruções, o tempo some antes mesmo da construção começar.</p></div><div className="shift-compare"><article><span>Sem orquestração</span><ul><li>Links espalhados em abas e favoritos</li><li>Prompt muda conforme o que você lembrou</li><li>Referência externa confundida com instrução</li><li>Revisão acontece tarde, depois do retrabalho</li></ul></article><article><span>Com o Orquestrador</span><ul><li>Escolha orientada pelo objetivo do site</li><li>Skills e referências aparecem separadas</li><li>Seleção revisada antes de chegar à IA</li><li>Processo reaproveitável no próximo projeto</li></ul></article></div></section>

    <section className="impact-section" id="impacto" aria-labelledby="impact-title"><div className="impact-copy"><h2 id="impact-title">Veja onde o tempo pode voltar para você.</h2><p>O simulador não inventa produtividade. Ajuste os três controles com a sua realidade e visualize a diferença entre procurar tudo do zero e trabalhar com uma seleção já organizada.</p></div><TimeEstimator /></section>

    <section className="experience-section" id="experimente" aria-labelledby="experience-title"><div className="experience-copy"><h2 id="experience-title">Você entende o produto usando, não lendo uma promessa.</h2><p>Escolha e retire opções neste exemplo. No painel completo, cada item explica quando usar, sua fonte e se é uma skill executável ou apenas uma referência externa.</p><Link className="text-action" href={user ? "/painel" : "/entrar?intent=signup"}>{user ? "Abrir o painel completo" : "Criar conta para continuar"}<span aria-hidden="true">→</span></Link></div><MarketingSelectorDemo /></section>

    <section className="transformation" aria-labelledby="transformation-title"><div className="transformation-copy"><h2 id="transformation-title">Do objetivo ao chat em três decisões visíveis.</h2><p>O sistema entrega valor antes de pedir configuração complexa: você entra, escolhe e confirma.</p></div><ol className="process-list"><li><span>1</span><div><h3>Defina o que precisa melhorar</h3><p>Design, segurança, desempenho, conteúdo ou conversão.</p></div></li><li><span>2</span><div><h3>Monte a combinação</h3><p>Use skills executáveis e referências externas claramente identificadas.</p></div></li><li><span>3</span><div><h3>Confirme antes de enviar</h3><p>Nada entra silenciosamente. Você mantém a decisão final sobre o projeto.</p></div></li></ol></section>

    <section className="responsibility-split" aria-labelledby="responsibility-title"><div><h2 id="responsibility-title">Por que escolher um sistema criado comigo.</h2><p>Você não compra um catálogo parado. O produto foi pensado por quem cria sites com IA e conhece a dor de alternar entre referências, prompts, revisão visual, segurança e desempenho no mesmo projeto.</p></div><dl><div><dt>Critério antes da quantidade</dt><dd>Cada recurso precisa ter função, fonte e momento de uso claros.</dd></div><div><dt>Decisão continua humana</dt><dd>O sistema organiza; você confere o que será aplicado antes do envio.</dd></div><div><dt>Site e chat conectados</dt><dd>O mesmo catálogo pode orientar o trabalho no painel e em clientes compatíveis com MCP.</dd></div><div><dt>Responsabilidade visível</dt><dd>Idealização e requisitos por Anny Gabrielly, @annygabb, com processo documentado e código aberto.</dd></div></dl></section>

    <section className="pricing-section" id="plano" aria-labelledby="pricing-title"><div className="pricing-copy"><h2 id="pricing-title">Comece completo. Continue por um valor menor.</h2><p>A ativação inclui os primeiros 30 dias para você montar o processo, testar no seu fluxo e usar o painel completo. Depois, a renovação mantém o acesso sem esconder o vencimento ou o cancelamento.</p></div><article className="pricing-card"><div className="price-first"><span>Ativação + 30 dias</span><strong>{moneyFromCents(ACTIVATION_PRICE_CENTS)}</strong><small>pagamento inicial</small></div><div className="price-renewal"><span>Depois</span><strong>{moneyFromCents(RENEWAL_PRICE_CENTS)}<em>/mês</em></strong><small>renovação cancelável pelo perfil</small></div><ul><li>Painel completo de skills e referências</li><li>Uso pelo site e MCP enquanto o período estiver pago</li><li>Perfil com vencimento, valor e cancelamento</li><li>E-mails de cadastro, pagamento e situação da assinatura</li></ul><Link className="button button--primary button--large" href={user ? "/pagamento" : "/entrar?intent=signup"}>{user ? "Ativar acesso" : "Começar meu processo"}</Link></article></section>

    <section className="final-cta"><p>Menos tempo procurando. Mais clareza para construir.</p><Link className="button button--outline button--large" href={user ? "/painel" : "/entrar?intent=signup"}>{user ? "Abrir painel" : "Começar agora"}</Link></section>
  </main><footer className="site-footer"><p>Seu próximo site começa com decisões mais claras.</p><div><strong>Orquestrador de Sites</strong><span>© 2026, Anny Gabrielly</span><nav aria-label="Links do rodapé"><Link href="/privacidade">Privacidade</Link><Link href="/termos">Termos</Link><Link href="/reembolso">Reembolso</Link><Link href="/cookies">Cookies</Link><a href="https://github.com/annygabb/Orquestrador-de-Sites" target="_blank" rel="noopener noreferrer">GitHub</a></nav></div></footer></>;
}
