import { escapeHtml } from "./html";

export type LifecycleEmailKind = "welcome" | "activation_paid" | "renewal_reminder" | "payment_overdue" | "access_suspended" | "subscription_canceled";

export function renderLifecycleEmail(kind: LifecycleEmailKind, name: string, manageUrl: string) {
  const content: Record<LifecycleEmailKind, { kicker: string; title: string; message: string; next: string; action: string }> = {
    welcome: { kicker: "VOCÊ ESTÁ DENTRO", title: "Seu processo começa agora.", message: "Sua conta foi criada. Entre no painel, conheça as opções e monte sua primeira seleção de skills.", next: "entre no painel e escolha o objetivo do seu próximo site.", action: "Abrir meu painel" },
    activation_paid: { kicker: "ACESSO LIBERADO", title: "Pagamento confirmado.", message: "Recebemos o pagamento e seu acesso já está ativo pelos próximos 30 dias.", next: "abra o painel e continue a seleção que deseja levar para o chat.", action: "Usar o Orquestrador" },
    renewal_reminder: { kicker: "FALTAM 3 DIAS", title: "Sua renovação está próxima.", message: "A renovação mensal vence em três dias. Você pode conferir o valor, o vencimento e a situação pelo perfil.", next: "revise os dados da cobrança e mantenha o acesso sem interrupção.", action: "Conferir renovação" },
    payment_overdue: { kicker: "PAGAMENTO PENDENTE", title: "A renovação venceu.", message: "Ainda não identificamos o pagamento. Regularize a cobrança para evitar que o painel e o acesso pelo chat sejam suspensos.", next: "acesse seu perfil e confira a cobrança pendente.", action: "Regularizar acesso" },
    access_suspended: { kicker: "ACESSO PAUSADO", title: "O período pago terminou.", message: "O painel e o MCP foram bloqueados porque a renovação não foi confirmada. Suas configurações continuam salvas.", next: "regularize a assinatura para voltar a usar o sistema.", action: "Reativar meu acesso" },
    subscription_canceled: { kicker: "RENOVAÇÃO CANCELADA", title: "Seu cancelamento foi registrado.", message: "A cobrança recorrente foi cancelada. Você continua com acesso até o fim do período que já pagou.", next: "consulte no perfil a data exata até quando o acesso permanece ativo.", action: "Ver minha assinatura" },
  };
  const item = content[kind];
  const safeName = escapeHtml(name);
  const safeManageUrl = escapeHtml(manageUrl);
  const greeting = safeName ? `Olá, <strong>${safeName}</strong>.` : "Olá.";
  return `<!doctype html><html lang="pt-BR"><body style="margin:0;background:#f2f5e9;color:#17270d;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f2f5e9;padding:24px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:580px;border:1px solid #d9decf;border-top:7px solid #a7ff20;border-radius:22px;background:#ffffff;overflow:hidden"><tr><td style="padding:34px 40px 18px"><table role="presentation" cellspacing="0" cellpadding="0"><tr><td style="width:48px;height:48px;border-radius:14px;background:#a7ff20;text-align:center;font-weight:900;color:#10160d">OS</td><td style="padding-left:14px"><strong style="display:block;font-size:18px;color:#10160d">ORQUESTRADOR</strong><span style="font-size:10px;letter-spacing:2px;color:#64705c">SKILLS PARA SITES COM IA</span></td></tr></table></td></tr><tr><td style="padding:18px 40px 34px"><p style="margin:0 0 18px;font-size:11px;line-height:1;letter-spacing:2px;color:#45642e">${item.kicker}</p><h1 style="margin:0 0 18px;max-width:430px;font-size:38px;line-height:1.05;letter-spacing:-1.5px;color:#17300b">${item.title}</h1><p style="margin:0 0 22px;font-size:16px;line-height:1.6;color:#3f473b">${greeting} ${item.message}</p><div style="margin:0 0 24px;border-left:3px solid #a7ff20;border-radius:0 12px 12px 0;background:#f3fae7;padding:16px 18px;font-size:14px;line-height:1.55;color:#34402d"><strong>Seu próximo passo:</strong> ${item.next}</div><a href="${safeManageUrl}" style="display:inline-block;border:2px solid #15200f;border-radius:10px;background:#a7ff20;padding:15px 22px;color:#10160d;font-size:15px;font-weight:800;text-decoration:none">${item.action} &nbsp;→</a></td></tr><tr><td style="border-top:1px solid #e5e8df;padding:22px 40px;color:#70786b;font-size:11px;line-height:1.55">Você recebeu este e-mail por ter uma conta no Orquestrador de Sites.<br>Idealização e requisitos por Anny Gabrielly.</td></tr></table></td></tr></table></body></html>`;
}
